---
plugin:
  author: puppetlabs
  id: spec_puppet
  display: Spec Puppet
  version: 0.1.0
  upstream_project_url: https://github.com/puppetlabs/puppetlabs_spec_helper

gem:
  build_tools: false
  name: [puppetlabs_spec_helper, rspec-puppet-facts]
  executable: rake

common:
  requires_git: true # suggested new
  can_validate: true
  needs_write_access: true
  default_args: [spec]
  help_arg: '--help'
  success_exit_code: 0
  interleave_stdout_err: false
